# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :clientipa => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => home + '/VirtualBox VMs/disks/sata1.vdi',
			:size => 5000,
			:port => 1
		}
        },
  },
  
  :serveripa => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.100',
        :disks => {
                :sata1 => {
                        :dfile => home + '/VirtualBox VMs/disks/sata2.vdi',
                        :size => 5000,
                        :port => 1
                }
        },
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "512"]
        end
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        
        box.vm.network "private_network", ip: boxconfig[:ip_addr]
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "serveripa"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
              yum install -y epel-release
	      yum update
              yum upgrade -y
	      yum install -y net-tools ipa-server ipa-server-dns bind bind-dyndb-ldap
              hostnamectl set-hostname ipa.domain.local
            SHELL
        when "clientipa"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
              yum install -y epel-release
              yum update
              yum upgrade -y
              yum -y install ipa-client nss-pam-ldapd
            systemctl restart network
            SHELL
        end

      end

  end
  
  
end
