# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "psql"
    master.vm.hostname = "master"
  end
  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "psql"
    slave.vm.hostname = "slave"
  end
  config.vm.define "backup" do |backup|
    backup.vm.network "private_network", ip: "192.168.50.12", virtualbox__intnet: "psql"
    backup.vm.hostname = "backup"
  end

end
