---
- name: create directory for nfs share
  file:
    path: /mnt/storage
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: copy exports
  copy: src=exports dest=/etc/exports
  notify: restart nfs-server

- name: copy nfs conf
  copy: src=nfs.conf dest=/etc/nfs.conf
  notify: restart nfs-server
- name: configure firewalld
  firewalld: port={{ item }} state=enabled permanent=yes immediate=yes
  with_items:
    - 111/tcp
    - 111/udp
    - 2049/tcp
    - 20048/udp
