# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :vm1 => {
        :box_name => "centos/7",
        :disks => {
                :sata1 => {
                        :dfile => home + '/VirtualBox VMs/disks/sata1.vdi',
                        :size => 5000,
                        :port => 1
                }
        },
        :net => [
              {ip: "192.168.12.10", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net12"},
              {ip: "192.168.16.10", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net16"},
              {ip: '10.1.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR0"},
                ]
  },
  :vm2 => {
        :box_name => "centos/7",
        :disks => {
                :sata1 => {
                        :dfile => home + '/VirtualBox VMs/disks/sata3.vdi',
                        :size => 5000,
                        :port => 1
                }
        },
        :net => [
              {ip: "192.168.12.9", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net12"},
              {ip: "192.168.20.10", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net20"},
              {ip: '10.2.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR1"},
                ]
  },
    :vm3 => {
        :box_name => "centos/7",
        :disks => {
                :sata1 => {
                        :dfile => home + '/VirtualBox VMs/disks/sata3.vdi',
                        :size => 5000,
                        :port => 1
                }
        },
        :net => [
              {ip: "192.168.16.9", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net16"},
              {ip: "192.168.20.9", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net20"},
              {ip: '10.3.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR2"},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "512"]
        end
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
          yum update
          yum install -y quagga
          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
          echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
          sysctl --system
        SHELL
        

      end

  end
  
  
end