nginx:
  image: kuvshinov/hw9snginx
  volumes:
    - ./src/html:/var/www
    - ./src/default.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
  links:
    - php
php:
  image: kuvshinov/hw9sphp
  volumes:
    - ./src/html:/var/www

