# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "mail" do |mail|
    mail.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "mail"
    mail.vm.network "forwarded_port", guest: 25, host: 25, auto_correct: true
    mail.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
    mail.vm.hostname = "mail"
  end
end
