---
- name: NGINX | Install and configure NGINX
  hosts: all
  become: true
  vars:
    nginx_listen_port: 8080  
  tasks:
    - name: NGINX | Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL Repo
      yum:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages
    - name: NGINX | Create NGINX config file from template
      template:
        src: ../../ansible/templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration
    - name: Filebeat | Download rpm
      get_url:
       url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.2-x86_64.rpm
       dest: /tmp/filebeat-7.5.2-x86_64.rpm
    - name: Filebeat | Install rpm
      yum:
       name: /tmp/filebeat-7.5.2-x86_64.rpm
       state: present
    - name: Filebeat | Enable nginx module
      command: filebeat modules enable nginx
    - name: Filebeat | Copy filebeat.yml
      template:
        src: ./filebeat.yml
        dest: /etc/filebeat/filebeat.yml
      notify:
        - restart filebeat
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    - name: restart filebeat
      systemd:
        name: filebeat
        state: restarted
        enabled: yes
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
