---
- name: create directory for nfs share
  file:
    path: /mnt/nfs-share
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'

- name: mount nfs share
  command: mount -o udp 192.168.50.10:/mnt/storage /mnt/nfs-share

- name: create upload directory
  file:
    path: /mnt/nfs-share/upload
    state: directory
  become_user: vagrant

